<?php
/**
 * Test class for Tag.
 * Generated by PHPUnit on 2013-02-19 at 11:44:09.
 */
use Primalbase\Tag\Tag;
use Primalbase\Tag\TagNodes;

class TagTest extends PHPUnit_Framework_TestCase
{
  protected function setUp()
  {
    Tag::$codeFormat = false;
  }

  protected function tearDown()
  {
  }

  public function testConstruct()
  {
    $this->assertEquals(get_class(Tag::a()), 'Primalbase\Tag\Tag');
    $this->assertEquals((string)Tag::a(), '<a></a>');
    $this->assertEquals((string)Tag::create('hoge', array('class' => 'fuga'), 'munya'), '<hoge class="fuga">munya</hoge>');
    $this->assertEquals((string)Tag::create('hoge', array('class' => 'fuga'), '<munya'), '<hoge class="fuga">&lt;munya</hoge>');
    $this->assertEquals((string)Tag::div('<hoge class="fuga">munya</hoge>'), '<div>&lt;hoge class=&quot;fuga&quot;&gt;munya&lt;/hoge&gt;</div>');

    $this->assertEquals((string)Tag::div(array('class' => 'span12')), '<div class="span12"></div>');
    $this->assertEquals((string)Tag::div(array('class' => 'span12'), 'test', Tag::span("inner")), '<div class="span12">test<span>inner</span></div>');
    $this->assertEquals((string)Tag::createInstanceArray('div', array(array('class' => 'span9'), 'array contents.')), '<div class="span9">array contents.</div>');
  }

  public function testMember()
  {
    $tag = Tag::table()->tagName('strong');
    $this->assertEquals($tag->getTagName(), 'strong');
    $this->assertEquals(Tag::table(array('class' => 'horizontal'))->attributes(), array('class' => 'horizontal'));
  }

  public function testAttr()
  {
    $this->assertEquals('<a href="http://www.yahoo.com">another</a>',
      (string)Tag::a('another')->attr('href', 'http://www.yahoo.com'));

    $this->assertEquals('<input name="require" required>',
      (string)Tag::input(array('name' => 'require'))->attr('required', true));

    $this->assertEquals('<input name="optional">',
      (string)Tag::input(array('name' => 'optional'))->attr('required', true)->attr('required'));

    $this->assertEquals('<input name="optional" class="form-control">',
      (string)Tag::input(array('name' => 'optional'))->attr('class')->addClass('form-control'));
  }

  public function testAttributes()
  {
    $this->assertEquals(
      '<div class="control-group"></div>',
      (string)Tag::div()->class('control-group'));

    $this->assertEquals(
      '<a href="http://www.google.com">here</a>',
      (string)Tag::a('here')->href('http://www.google.com'));

    $this->assertEquals(
      '<input required>',
      (string)Tag::input()->required(true));
  }

  public function testUpdateAttributes()
  {
    $this->assertEquals('<input type="text" required>',
      (string)Tag::input()->updateAttributes(array('type' => 'text', 'required')));

  }

  public function testAppend()
  {
    $this->assertEquals('<div><span>content</span></div>', (string)Tag::div()->append(Tag::span('content')));
    $this->assertEquals('<div><span>content1</span><span>content2</span></div>', (string)Tag::div(Tag::span('content1'))->append(Tag::span('content2')));
    $this->assertEquals('<ul><li>item1</li><li>item2</li>outer</ul>', (string)Tag::ul()->append(TagNodes::create(Tag::li('item1'), Tag::li('item2')), 'outer'));

    $this->assertEquals((string)TagNodes::create()->append('<strong></strong>'), '&lt;strong&gt;&lt;/strong&gt;');
    $this->assertEquals((string)Tag::div()->append('<strong></strong>'), '<div>&lt;strong&gt;&lt;/strong&gt;</div>');

    $this->assertEquals('<div hoge>fuga</div>',
      (string)Tag::div()->append('fuga', array('hoge')));

    Tag::body()->append($p = Tag::div());
    $this->assertEquals('body', $p->parent()->getTagName());
    $this->assertEquals('<div></div>', (string)$p);
    $this->assertEquals('<body><div></div></body>', (string)$p->close());
    $this->assertEquals('<body><div></div></body>', (string)$p->parent());
  }

  public function testAppendHtml()
  {
    $this->assertEquals('<div>&lt;span id=&quot;append_html&quot;&gt;test&lt;/span&gt;</div>', (string)Tag::div()->append('<span id="append_html">test</span>'));
    $this->assertEquals('<div><span id="append_html">test</span></div>', (string)Tag::div()->appendHtml('<span id="append_html">test</span>'));
    $this->assertEquals('<div><span id="append_html">test1</span><span id="append_html">test2</span></div>', (string)Tag::div()->appendHtml('<span id="append_html">test1</span>')->appendHtml('<span id="append_html">test2</span>'));
  }

  public function testPrepend()
  {
    $this->assertEquals('<div><span>content</span></div>', (string)Tag::div()->prepend(Tag::span('content')));
    $this->assertEquals('<div><span>content1</span><span>content2</span></div>', (string)Tag::div(Tag::span('content2'))->prepend(Tag::span('content1')));
    $this->assertEquals('<ul><li>item1</li><li>item2</li>outer</ul>', (string)Tag::ul()->prepend(TagNodes::create(Tag::li('item1'), Tag::li('item2'), 'outer')));

    $this->assertEquals((string)TagNodes::create()->prepend('<strong></strong>'), '&lt;strong&gt;&lt;/strong&gt;');
    $this->assertEquals((string)Tag::div()->prepend('<strong></strong>'), '<div>&lt;strong&gt;&lt;/strong&gt;</div>');
  }

  public function testPrependHtml()
  {
    $this->assertEquals('<div>&lt;span id=&quot;append_html&quot;&gt;test&lt;/span&gt;</div>', (string)Tag::div()->prepend('<span id="append_html">test</span>'));
    $this->assertEquals('<div><span id="append_html">test</span></div>', (string)Tag::div()->prependHtml('<span id="append_html">test</span>'));
    $this->assertEquals('<div><span id="append_html">test1</span><span id="append_html">test2</span></div>', (string)Tag::div()->prependHtml('<span id="append_html">test2</span>')->prependHtml('<span id="append_html">test1</span>'));
  }

  public function testHtml4()
  {
    Tag::$DocType = 'Primalbase\Tag\DocType\Html4';
    $this->assertEquals((string)Tag::br(), '<br>');
    $this->assertEquals('<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">', Tag::docType());
  }

  public function testXhtml()
  {
    Tag::$DocType = 'Primalbase\Tag\DocType\Xhtml';
    $this->assertEquals((string)Tag::br(), '<br />');
    $this->assertEquals('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">', Tag::docType());
  }

  public function testHtml5()
  {
    Tag::$DocType = 'Primalbase\Tag\DocType\Html5';
    $this->assertEquals((string)Tag::br(), '<br>');
    Tag::$codeFormat = true;
    $this->assertEquals('<!DOCTYPE html>'.PHP_EOL, Tag::docType());
    Tag::$codeFormat = false;
    $this->assertEquals('<!DOCTYPE html>', Tag::docType());
  }

  public function testClassManipulation()
  {
    $this->assertFalse(Tag::div()->hasClass('label'));
    $this->assertTrue(Tag::div()->addClass('label')->hasClass('label'));
    $this->assertTrue(Tag::div()->class('label1 label2')->hasClass('label2'));
    $this->assertFalse(Tag::div()->class('label1 label2')->hasClass('label3'));
    $this->assertEquals((string)Tag::div()->addClass('span1'), '<div class="span1"></div>');
    $this->assertEquals((string)Tag::div(array('class' => 'span1 label'))->removeClass('span1'), '<div class="label"></div>');
    $this->assertEquals((string)Tag::div()->addClass('span1', 'label'), '<div class="span1 label"></div>');
    $this->assertEquals((string)Tag::div(array('class' => 'span1 label'))->removeClass(array('label')), '<div class="span1"></div>');
  }

  public function testCodeFormat()
  {
    Tag::$codeFormat = true;
    $this->assertEquals((string)Tag::div()->addClass('span1'), '<div class="span1">'.PHP_EOL.'</div>'.PHP_EOL);
    $this->assertEquals((string)Tag::div('contents')->addClass('span1'), '<div class="span1">'.PHP_EOL.'  contents'.PHP_EOL.'</div>'.PHP_EOL);
    $this->assertEquals((string)Tag::br(), '<br>'.PHP_EOL);
    $this->assertEquals((string)Tag::div('contents'), '<div>'.PHP_EOL.'  contents'.PHP_EOL.'</div>'.PHP_EOL);
    $this->assertEquals((string)Tag::div(Tag::div(Tag::span('content'))), '<div>'.PHP_EOL.'  <div>'.PHP_EOL.'    <span>content</span>'.PHP_EOL.'  </div>'.PHP_EOL.'</div>'.PHP_EOL);
    $this->assertEquals((string)Tag::span(Tag::span(), Tag::span()), '<span><span></span><span></span></span>'.PHP_EOL);
  }

  public function testUpdate()
  {
    $this->assertEquals((string)Tag::div(array('class' => 'span1', 'id' => 'update'), 'update')->updateFromArray(array(array('class' => 'span2'))), '<div class="span2" id="update">update</div>');
    $this->assertEquals((string)Tag::div(array('class' => 'span1', 'id' => 'update'), 'update')->updateFromArray(array(Tag::span('new'))), '<div class="span1" id="update">update<span>new</span></div>');
  }

  public function testParent()
  {
    $root = Tag::div()->id('root');
    $this->assertNull($root->getParent());
    $root->append($second = Tag::div()->id('second'));
    $this->assertEquals('<div id="second"></div>', (string)$second);
    $this->assertEquals('<div id="root"><div id="second"></div></div>', (string)$second->close());
    $second->append($third = Tag::div()->id('third'));
    $this->assertEquals('<div id="third"></div>', (string)$third);
    $this->assertEquals('<div id="second"><div id="third"></div></div>', (string)$third->close());
    $this->assertEquals('<div id="root"><div id="second"><div id="third"></div></div></div>', (string)$third->end());
  }
}

