<?php
set_include_path(implode(PATH_SEPARATOR, array(
  dirname(__FILE__).'/../',
  get_include_path(),
)));

require_once 'Tag.php';

/**
 * Test class for Tag.
 * Generated by PHPUnit on 2013-02-19 at 11:44:09.
 */
class TagTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Tag
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Tag;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testHtml4()
    {
      Tag::$DocType = 'html4';
      $this->assertEquals((string)Tag::br(), '<br>');
    }
    
    public function testXhtml()
    {
      Tag::$DocType = 'xhtml';
      $this->assertEquals(get_class(Tag::a()), 'Tag');
      $this->assertEquals(Tag::a()->tagName(), 'a');
      $this->assertEquals(Tag::a()->attributes(), array());
      $this->assertEquals((string)Tag::a(), '<a></a>');
      $this->assertEquals((string)Tag::br(), '<br />');
    }
    
    public function testHtml5()
    {
      Tag::$DocType = 'html5';
      $this->assertEquals((string)Tag::br(), '<br>');
    }
}
?>
